# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
 - openjdk14

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
 global:
  - CODECOV_TOKEN="74362226-3b83-4d4d-bce2-ccba2c9c3a92"